# Generated by Django 5.2.3 on 2025-06-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('passyear', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('selectcourse', models.CharField(choices=[('python', 'Python Full Stack'), ('java', 'Java Full Stack'), ('web', 'Web Development'), ('ml', 'Machine Learning')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('durations', models.CharField(max_length=10)),
                ('fees', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
